### ISSUE TITLE
Bug 2

### ISSUE THREAD

**Issue by Aiwe83** [Aiwe83/HobbiToon#4]
Cuando en el menú voy agregar raza inmediatamente me pregunta por habitad sin poder colocar raza. No se la razón de ese error.

**Comment by pmcder** [comment]
Resolvi esto. Me lo puede asignar y te mando un pull request. habla ingles ? si eso te mando un link con una descripción de la causa de esto. si no, se lo describo yo en español si gusta ? espero tu respuesta.

**Comment by Aiwe83** [comment]
> Resolvi esto. Me lo puede asignar y te mando un pull request. habla ingles? si eso te mando un link con una descripción de la causa de esto. si no, se lo describo yo en español si gusta? espero tu respuesta.

**Comment by Aiwe83** [comment]
> > Resolvi esto. Me lo puede asignar y te mando un pull request. habla ingles? si eso te mando un link con una descripción de la causa de esto. si no, se lo describo yo en español si gusta? espero tu respuesta.

Vale muchas gracias @pmcder soy muy nuevo aun en esto te he puesto como colaborador de proyecto también , Saludos.
